language: node_js
node_js: stable
addons:
  ssh_known_hosts: 
    - github.com
    - 192.30.253.113
    - gitee.com
    - 120.55.226.24
    - 94.191.80.51
before_install:
  - openssl aes-256-cbc -K $encrypted_a8fc4b24cb2e_key -iv $encrypted_a8fc4b24cb2e_iv -in github_travis.enc -out ~\/.ssh/github_travis -d
install:
  - npm install gitbook-cli -g
script:
  - gitbook install
  - gitbook build
  - ls
  - scp -r _book/  git@94.191.80.51:/usr/local/www/book
after_script:
  - echo "Hello World"
branches:
  only:
  - master
notifications:
  email:
  - idrools007@gmail.com
  - zxh877027287@gmail.com
  on_success: change
  on_failure: always
