language: node_js
node_js: stable
addons:
  ssh_known_hosts:
  - github.com
  - 192.30.253.113
  - gitee.com
  - 120.55.226.24
  - 94.191.80.51
install:
- npm install gitbook-cli -g
script:
- gitbook install
- gitbook build
before_install:
- echo "before_install Hello World"
- openssl aes-256-cbc -K $encrypted_a8fc4b24cb2e_key -iv $encrypted_a8fc4b24cb2e_iv
  -in github_travis.enc -out ~/.ssh/github_travis -d
- chmod 600 ~/.ssh/github_travis
- echo -e "Host 94.191.80.51\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/github_travis" >> ~/.ssh/config
after_script:
- scp -o stricthostkeychecking=no -r _book/  root@94.191.80.51:/usr/local/www/book
- echo "after_script Hello World"
branches:
  only:
  - master
notifications:
  email:
  - idrools007@gmail.com
  - zxh877027287@gmail.com
  on_success: change
  on_failure: always
#idrools/book:
#- openssl aes-256-cbc -K $encrypted_a8fc4b24cb2e_key -iv $encrypted_a8fc4b24cb2e_iv
#  -in github_travis.enc -out ~/.ssh/github_travis -d
